services:
  api:
    environment:
      DEBUG: "false"
    volumes:
      - "./src/prodik/infrastructure/db/migrations/versions/:/prodik/src/prodik/infrastructure/db/migrations/versions/"

  postgres:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 15s
      timeout: 15s
      retries: 5