[api]
host = "0.0.0.0"
port = 8000

persistence = "postgresql+asyncpg://postgres:admin_password@persistence.literally.io:5432/postgres"
secret = "AAAAAAAAAABBBBBBBBBB"
expires_in = 3600

[object_storage]
url = "http://files.literally.io:9000"
secret_key = "your_admin_secret_key"
access_key = "your_admin_access_key"
region = "us-east-1"
bucket = "machine-learning"
temp_directory = "src/prodik/infrastructure/file/temp"

[keycloak]
client_id = "your_client_id"
client_secret = "your_client_secret"