[api]
host = "0.0.0.0"
port = 8000

persistence = "postgresql+asyncpg://postgres:admin_password@persistence.literally.io:5432/postgres"
secret = "AAAAAAAAAABBBBBBBBBB"
expires_in = 3600

[object_storage]
url = "files.literally.io"
secret_key = "admin_password"
access_key = "admin"
region = "RU-SPB"
bucket = "ml"

[keycloak]
client_id = "your_client_id"
client_secret = "your_client_secret"