from typing import Protocol
from uuid import UUID

from prodik.domain.credentials import (
    IP,
    LocalAuthorization,
    OAuthAuthorization,
    UserSession,
)
from prodik.domain.user import Email, User, UserId, Username


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_uuid(self, uuid: UUID) -> User | None: ...
    async def get_by_username(self, username: Username) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...


class LocalAuthorizationRepository(Protocol):
    async def create(self, local_authorization: LocalAuthorization) -> None: ...
    async def update(self, local_authorization: LocalAuthorization) -> None: ...
    async def get_by_user_id(self, id: UserId) -> LocalAuthorization: ...


class OAuthAuthorizationRepository(Protocol):
    async def get_by_user_id(self, user_id: UserId) -> OAuthAuthorization | None: ...


class UserSessionRepository(Protocol):
    async def get_by_user_id_and_ip(self, id: UserId, ip: IP) -> UserSession | None: ...
    async def get_all_by_user_id(self, id: UserId) -> list[UserSession]: ...
    async def create(self, user_session: UserSession) -> None: ...
    async def update(self, user_session: UserSession) -> None: ...
    async def update_many(self, user_sessions: list[UserSession]) -> None: ...
