from typing import Protocol
from uuid import UUID

from prodik.domain.user import User


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_uuid(self, uuid: UUID) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
