from prodik.application.errors import ApplicationError


class DomainUserValidationError(ApplicationError): ...


class NotEnoughRightsError(ApplicationError): ...


class UsernameTooLongError(DomainUserValidationError): ...


class UsernameTooShortError(DomainUserValidationError): ...


class FirstNameTooLongError(DomainUserValidationError): ...


class FirstNameTooShortError(DomainUserValidationError): ...


class SecondNameTooLongError(DomainUserValidationError): ...


class SecondNameTooShortError(DomainUserValidationError): ...


class AgeTooSmallError(DomainUserValidationError): ...


class AgeTooBigError(DomainUserValidationError): ...


class InvalidUsernameFormatError(DomainUserValidationError): ...


class EmailInvalidFormatError(DomainUserValidationError): ...
