from prodik.application.errors import ApplicationError


class UsernameTooLongError(ApplicationError): ...


class UsernameTooShortError(ApplicationError): ...


class FirstNameTooLongError(ApplicationError): ...


class FirstNameTooShortError(ApplicationError): ...


class SecondNameTooLongError(ApplicationError): ...


class SecondNameTooShortError(ApplicationError): ...


class AgeTooSmallError(ApplicationError): ...


class AgeTooBigError(ApplicationError): ...


class InvalidUsernameFormatError(ApplicationError): ...


class EmailInvalidFormatError(ApplicationError): ...
