from typing import Protocol

from prodik.domain.credentials import (
    IP,
    UserSession,
)
from prodik.domain.user import UserId


class UserSessionRepository(Protocol):
    async def revoke_all_by_user_id(self, id: UserId) -> None: ...
    async def get_by_user_id_and_ip(self, id: UserId, ip: IP) -> UserSession | None: ...
    async def get_all_by_user_id(self, id: UserId) -> list[UserSession]: ...
    async def create(self, user_session: UserSession) -> None: ...
    async def update(self, user_session: UserSession) -> None: ...
    async def update_many(self, user_sessions: list[UserSession]) -> None: ...
    async def get_by_token(self, refresh_token: str) -> UserSession | None: ...
