from typing import Protocol

from prodik.domain.user import Email, User, UserId, Username


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_uuid(self, id: UserId) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def get_all(self, page: int, size: int) -> list[User]: ...
    async def get_by_username(self, username: Username) -> User | None: ...
