"""raw

Revision ID: 1c11c5c81c78
Revises: 45dacf398621
Create Date: 2026-04-21 09:35:46.739173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c11c5c81c78'
down_revision: Union[str, Sequence[str], None] = '45dacf398621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_input_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('task_record', 'result',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_record', 'result',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_table('raw_input_record')
    # ### end Alembic commands ###
