"""datetime

Revision ID: 28a759e4dbcb
Revises: 9f73f4fa5595
Create Date: 2026-04-17 11:26:02.437208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28a759e4dbcb"
down_revision: Union[str, Sequence[str], None] = "9f73f4fa5595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "local_authorization", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "local_authorization", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "oauth_authorization", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "oauth_authorization", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("task_record", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("task_record", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column(
        "user_account", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "user_account", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "user_session", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "user_session", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_session", "updated_at")
    op.drop_column("user_session", "created_at")
    op.drop_column("user_account", "updated_at")
    op.drop_column("user_account", "created_at")
    op.drop_column("task_record", "updated_at")
    op.drop_column("task_record", "created_at")
    op.drop_column("oauth_authorization", "updated_at")
    op.drop_column("oauth_authorization", "created_at")
    op.drop_column("local_authorization", "updated_at")
    op.drop_column("local_authorization", "created_at")
    # ### end Alembic commands ###
