"""cascase

Revision ID: 45dacf398621
Revises: d5723b3e7726
Create Date: 2026-04-19 09:00:52.426472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45dacf398621'
down_revision: Union[str, Sequence[str], None] = 'd5723b3e7726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('local_authorization_user_id_fkey'), 'local_authorization', type_='foreignkey')
    op.create_foreign_key(None, 'local_authorization', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_record_owner_id_fkey'), 'task_record', type_='foreignkey')
    op.create_foreign_key(None, 'task_record', 'user_account', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_session_user_id_fkey'), 'user_session', type_='foreignkey')
    op.create_foreign_key(None, 'user_session', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.create_foreign_key(op.f('user_session_user_id_fkey'), 'user_session', 'user_account', ['user_id'], ['id'])
    op.drop_constraint(None, 'task_record', type_='foreignkey')
    op.create_foreign_key(op.f('task_record_owner_id_fkey'), 'task_record', 'user_account', ['owner_id'], ['id'])
    op.drop_constraint(None, 'local_authorization', type_='foreignkey')
    op.create_foreign_key(op.f('local_authorization_user_id_fkey'), 'local_authorization', 'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###
