"""initial

Revision ID: 9f73f4fa5595
Revises:
Create Date: 2026-04-17 09:55:29.467941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f73f4fa5595"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.VARCHAR, nullable=False),
        sa.Column("first_name", sa.VARCHAR, nullable=False),
        sa.Column("last_name", sa.VARCHAR, nullable=False),
        sa.Column("email", sa.VARCHAR, nullable=False),
        sa.Column("age", sa.INTEGER, nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "MODERATOR", name="userrole"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DEACTIVATED", name="userstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "local_authorization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_authorization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DEPRECATED", "PENDING", "DONE", name="taskstate"),
            nullable=False,
        ),
        sa.Column(
            "input_type", sa.Enum("FILE", "RAW", name="inputtype"), nullable=False
        ),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("result", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip", sa.String(length=36), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REVOKED", "ACTIVE", name="usersessionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_session")
    op.drop_table("task_record")
    op.drop_table("oauth_authorization")
    op.drop_table("local_authorization")
    op.drop_table("user_account")
    # ### end Alembic commands ###
