"""file

Revision ID: a916553a05fb
Revises: 1c11c5c81c78
Create Date: 2026-04-22 10:29:32.789253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a916553a05fb'
down_revision: Union[str, Sequence[str], None] = '1c11c5c81c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_input_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_input_record')
    # ### end Alembic commands ###
