from prodik.application.errors import ApplicationError


class InvalidCredentialsError(ApplicationError): ...


class UserSessionRevokedError(ApplicationError): ...


class AccessTokenExpiredError(ApplicationError): ...


class UserDeactivatedError(ApplicationError): ...


class UserAlreadyExistsError(ApplicationError): ...


class UserSessionExpiredError(ApplicationError): ...


class UnsupportedProviderError(ApplicationError): ...


class LocalAuthorizationNotFoundError(ApplicationError): ...


class UserSessionNotFoundError(ApplicationError): ...
